#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#### Customize to your needs...
### Zsh help
# ref: caveats in $brew info zsh
# and http://zsh.sourceforge.net/Doc/Release/User-Contributions.html#Accessing-On_002dLine-Help
# unalias run-help
# autoload run-help
HELPDIR=/usr/local/share/zsh/help

### Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
fi

### Environmental Variables
## API keys
# Keep keys out of public dotfiles repo by sourcing from local file. 
source "$HOME/.ssh/api"

## node.js
# Set n node version management location
export N_PREFIX=/opt/nodejs
# Set npm global install location
export NODE_PATH=/opt/nodejs/lib/node_modules
# nolo = node local -- Use 'npm bin' to execute local project binaries 
alias nolo='PATH=$(npm bin):$PATH'

## Pyenv
# enable shims and autocompletion
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
# use Homebrew's directories rather than ~/.pyenv
export PYENV_ROOT=/usr/local/opt/pyenv
## Pyenv-virtualenv
# enable auto-activation
if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi

## Amazon Web Services CLI
# source completions
source /usr/local/share/zsh/site-functions/_aws

### Custom Paths

### Go - Golang
## GVM - Golang Version Manager - https://github.com/moovweb/gvm
# Line originally appended to .zshrc by gvm/master/binscripts/gvm-installer:
# [[ -s "/Users/remy/.gvm/scripts/gvm" ]] && source "/Users/remy/.gvm/scripts/gvm"
export PATH=/Users/remy/.gvm/bin:$PATH

## set system Go installed via Homebrew
# set $GOPATH and $PATH out of Homebrew 
# version control under /usr/local
export GOPATH=/opt/go
export PATH=$PATH:$GOPATH/bin
# Add Golang commands within Cellar to $PATH
export PATH=$PATH:/usr/local/opt/go/libexec/bin

## Homebrew
# Path exported ahead of system by zprezto in ~/.zlogin
# export PATH=/usr/local/bin:/usr/local/sbin:$PATH

## User scripts 
# Append ~/bin to PATH
export PATH=$PATH:$HOME/bin

#Remove duplicates from Path
typeset -U PATH

### Functions

## One-line MySQL Database and User creation
# Source: http://www.commandlinefu.com/commands/view/12620/create-a-database-with-user-and-pass-without-hassle.
# Usage: mysqlcreatedb `database` `database-user` `database-password`
function mysqlcreatedb () { mysqladmin -u root -p create $1 && mysql -u root -p -e "GRANT ALL ON $1.* TO '$2'@'localhost' IDENTIFIED BY '$3';" ; }

## Take
# Create a new directory and change to it, will create intermediate directories as required.
# Forked from Oh-My-ZSH
# https://github.com/robbyrussell/oh-my-zsh/blob/958c8f439058c2c253434a0860d29bf6c11cd559/lib/functions.zsh
function take() {
  mkdir -p $1
  cd $1
}

### Aliases
## count
# return count of piped in list
alias cnt='wc -l'

## functions
# list all functions
alias listfunc='print -l ${(ok)functions}'

## ls 
# Return number of files are in current directory:
alias lno='ls | wc -l'
# Return 
alias ll='ls -alhAFG'

### Git
## Git commands
alias gitlog='git log --oneline --decorate --graph'
alias syncgit='git fetch src; git rebase src/master'
alias gits='git status'
#
## Github
# test github user authentication
alias testgithub='ssh -T git@github.com'
#
## Hub for Github
# alias hub as git - https://github.com/github/hub#aliasing
eval "$(hub alias -s)"

## Golang working directories
# Work
alias gowork='cd $GOPATH/src/rootandflow.com'
# Practice
alias goprac='cd $GOPATH/src/rootandflow.com/practice'

## Cache
alias flushdns='dscacheutil -flushcache; sudo killall -HUP mDNSResponder'

## Node and npm
# List global installed packages
alias ng='npm list -g --depth=0'
# increase depth
alias ng1='npm list -g --depth=1'
alias ng2='npm list -g --depth=2'
alias ng3='npm list -g --depth=3'

## Password Generation
# Generate rsa key pair with default parameters
alias keygen='ssh-keygen -b 4096 -t rsa -f id_rsa -P ""'
# Generate random password with safe character set
# 16 characters
alias 16pas='openssl rand -base64 16 |md5 |head -c16;echo'
# 32 characters
alias 32pas='openssl rand -base64 32 |md5 |head -c32;echo'

## Vagrant
alias vmshl='cd ~/webdev/vagrant-local && vagrant ssh'

## Zip and Unzip
# Unzip all archives in current directory; remove archives.
alias unzipall='unzip \*.zip; rm -rf *.zip;[[ -d __MACOSX ]] && rm -rf __MACOSX'
